"""Opaque identifiers used to correlate one extraction operation."""

from __future__ import annotations

import re
import uuid

_CORRELATION_ID_PATTERN = re.compile(r"^extract-[0-9a-f]{32}$")


def new_extraction_correlation_id() -> str:
    """Return a fresh correlation id that carries no source identity.

    The id is intentionally random.  Agent ids, episode ids, schemas, domains,
    and source text must not be encoded in a durable correlation value because
    routed jobs can otherwise collide and audit records can disclose data.
    """
    return f"extract-{uuid.uuid4().hex}"


def normalize_extraction_correlation_id(value: object | None) -> str:
    """Keep only code-owned ids; replace absent or legacy values.

    The accepted value is deliberately narrower than the task argument type:
    callers may receive arbitrary legacy JSON, but only an id generated by
    :func:`new_extraction_correlation_id` can safely preserve audit lineage.
    Invalid values are discarded without logging so old ids cannot leak into
    new audit records.
    """
    if isinstance(value, str) and _CORRELATION_ID_PATTERN.fullmatch(value):
        return value
    return new_extraction_correlation_id()
